language: swift
osx_image: xcode10.2
before_script:
  - swift package generate-xcodeproj
script:
  - xcodebuild -quiet -project Complex.xcodeproj -scheme Complex-Package -sdk macosx -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^Complex$' -F 'Complex'
