language: swift
osx_image: xcode10.2
before_script:
  - swift package generate-xcodeproj
script:
  - xcodebuild -project Complex.xcodeproj -scheme Complex-Package -enableCodeCoverage YES build test
after_success:
  - bash <(curl -s https://codecov.io/bash)

